
description: I love you for kinginiii oooh oooo
author:
  name: Sreenand
  email: sreenand676@gmail.com
theme: minima
minima:
  skin: classic
  social_links:
    - platform: github
      user_url: https://github.com/sreenand676-boop
    # Add more social links here later
